name: Testing commits
on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.adoc'
      - 'CONTRIBUTING.adoc'
jobs:
  job1-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Tests and coverage report
        run: ./tests/test.sh
        shell: bash {0}
