name: Testing commits
on: push
jobs:
  job1-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Tests and coverage report
        run: ./tests/test.sh
        shell: bash {0}
      - name: Archive dist package
        uses: actions/upload-artifact@v2
        with:
          path: artifacts/bdm-*.tar.gz
          retention-days: 5
      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: artifacts/coverage
